### ISSUE TITLE
AIM Handshake

### ISSUE THREAD

**Issue by jeffmcaffer** [autosportlabs/AnalogX#1]
I'm moving a bunch of RaceCapture sensors to a car with an AiM MXG 1.2 and picked up an AnalogX to connect as a CAN expansion module. Unfortunately the MXG does not seem to recognize the AnalogX. I have verified the connections, the AnalogX has 3.3v at the pads on the back and that the sensors are powered (5V) and the signal voltage is varying as the sensor is varied.

It seems like the AnalogX is simply not being discovered on the CAN bus. I tried both 500K and 1M baud rates and am using the default BASE ID. In RaceStudio 3 I added a CAN expansion and selected the AIM "Channel Expansion" module (the only real choice). The UI has a facility to set the "Expansion serial number". Not 100% sure what that is but I set it to the BASE ID (in decimal as the UI does not accept alphas). The RaceStudio "Get Expansion Serial Number" operation does not detect any "compatible expansion modules".

My naive thought is that the MXG is looking for particular values from the "expansion" units and that the AnalogX is not responding as desired. This would not be a bug per se but does limit/qualify the AIM support listed on the product page https://www.autosportlabs.com/product/analogx-4-channel-analog-to-can-interface/

Have I just been doing this wrong or there a feature to be added?

**Comment by brentpicasso** [comment]
Recommend you test with a generic CAN logger to verify AnalogX is emitting CAN data as expected.  You can use RaceCapture's can bus logger lua script  (https://wiki.autosportlabs.com/CAN_Bus_logger) or a generic CAN to USB logging device. 

You can tap your CAN logger into the CAN bus *while* connected to the AIM device, which can prove the AIM device is receiving the CAN data.  

If CAN data is broadcasted correctly, then you can contact AIM for further help with their CAN mapping capability.
